packageExtensions:
  "@theme-ui/theme-provider@*":
    peerDependencies:
      "@theme-ui/css": "^0.3.1"

  "gatsby@*":
    peerDependencies:
      "babel-plugin-polished": "^1.0.0"

  "dedent.macro@*":
    dependencies:
      "dedent": "^0.7.0"
      "babel-plugin-macros": "^2.8.0"
